work_dir: '001_resnet18'

data:
  params:
    idx_fold: -1 # for 5 fold
    num_folds: 5
  num_classes: 186

model:
  arch: 'Classification'
  name: 'resnet18'
  pretrained: 'imagenet'

train:
  batch_size: 32
  num_epochs: 1800
  early_stop_patience: 10

test:
  batch_size: 128
  best_threshold: 0.5

transforms:
  train:
    HorizontalFlip: False
    VerticalFlip: False
    Cutout:
      num_holes: 5
      hole_size: 25
    RandomCropScale: False
    Noise: False
    Contrast: False
  test:
    HorizontalFlip: False
    VerticalFlip: False
    Cutout:
      num_holes: 0
      hole_size: 256//10
    RandomCropScale: False

loss:
  name: "Grapheme"
  params:
    grapheme_weight: 1.0
    vowel_weight: 1.0
    consonant_weight: 1.0
optimizer:
  name: 'Adam'
  params:
    base_lr: 0.0001
    fresh_lr: 0.001


scheduler:
  name: 'plateau'
